# Book settings
title: Pacific Observatory
author: World Bank
logo: images/logo.png

repository:
  url: https://github.com/worldbank/pacific-observatory
  branch: main

exclude_patterns: [file-types/include-rst.rst]

# Bibliography settings
bibtex_bibfiles:
  - references.bib

sphinx:
  config:
    bibtex_reference_style: author_year
    html_extra_path: ['images']
    html_show_copyright: false
    html_last_updated_fmt: "%b %d, %Y"


html:
  home_page_in_navbar: true
  use_edit_page_button: true
  use_repository_button: true
  use_issues_button: true
  baseurl: https://github.com/worldbank/pacific-observatory

execute:
  execute_notebooks: "auto"
  allow_errors: true
  timeout: 60
  exclude_patterns:
    - '*tsa*'
    - '*model*'
    - '*ensemble*'
    - '*combo*'
    - '*forecast*'

# launch_buttons:
#   colab_url: "https://colab.research.google.com"

latex:
  latex_engine: xelatex
  latex_documents:
    targetname: book.tex
  use_jupyterbook_latex: true
